### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'get_shape'

### ISSUE THREAD

**Issue by liusidi** [ethanygao/NDDR-CNN#2]
Excuse me，It's error when I use this module.The shape I entered is torch.Size([2, 64, 144, 192])。

**Comment by ethanygao** [comment]
This repo is build on Tensorflow 1.4.0 or 1.4.1.
